### ISSUE TITLE
Retain zoom and position after auto-reload

### ISSUE THREAD

**Issue by georgetian3** [tomoki1207/vscode-pdfviewer#118]
After compiling LaTeX to PDF, the PDF viewer reloads, but resets zoom to 'Automatic Zoom', and the position goes back to the first page of the PDF.

Is there any way to retain the zoom and position after a reload?

**Comment by thatonearchguy** [comment]
Hello, I still have this issue with the latest version of the extension - it just boots me right to the top of the PDF. I am happy to provide debug logs if you show me how.

**Comment by ani-per** [comment]
I also have this issue. Despite setting the default scale to `page-fit`, the viewer always sticks with "Automatic".
