### ISSUE TITLE
Failed to open pdf size of 6 mb

### ISSUE THREAD

**Issue by nitishxp** [tomoki1207/vscode-pdfviewer#12]
I am unable to open the pdf size of 6mb or pdf which contain the pages approx to 300.
Whole content are being displayed as binary

**Comment by samraw83** [comment]
I had a 5 mb pdf file, it took time around 15 mins, to load but it did finally. have patience. :)

**Comment by tomoki1207** [comment]
Since VSCode decides whether to treat the file as text or binary, at this timing this extension can not do anything.
FYI, It might been fixed cause VSCode was updated.
