### ISSUE TITLE
Clicking links doesn't work

### ISSUE THREAD

**Issue by jleclanche** [tomoki1207/vscode-pdfviewer#13]
Clicking links (hrefs) in a pdf should open the browser, instead nothing happens.

**Comment by tomoki1207** [comment]
@neilsustc Thank you for report.
The links that not working are URL or absolute/relative file path or both?

**Comment by jleclanche** [comment]
http/https urls. Didn't test with file links.

**Comment by tomoki1207** [comment]
I'm sorry, but if it still happens, please reopen it.
