### ISSUE TITLE
PDF viewing broken in VSCode 1.14.0

### ISSUE THREAD

**Issue by deGravity** [tomoki1207/vscode-pdfviewer#14]
I just updated to VSCode 1.14.0 an vscode-pdf stopped working. The context menu still exists, and will open a new tab, but the tab is empty. Reverting to VSCode 1.13 restored functionality.

**Comment by tomoki1207** [comment]
@deGravity Thank you for reporting and sorry for late response.
It have been broken even ver.1.14.1?
Maybe it recovered related [this issue](https://github.com/Microsoft/vscode/issues/30464).

**Comment by deGravity** [comment]
It looks like 1.14.1 fixed it. Thanks!
