### ISSUE TITLE
v1.2.1 break Chinese characters display

### ISSUE THREAD

**Issue by heziiop** [tomoki1207/vscode-pdfviewer#148]
In v1.2.1,  Chinese characters can't be rendered correctly.
![image](https://user-images.githubusercontent.com/25722077/208356479-c3ad09fb-0da8-4772-8877-b582bc6d30be.png)

while in v1.2.0, it works good.
![image](https://user-images.githubusercontent.com/25722077/208356613-0c8cb161-feea-430b-baa7-0e511a3656c0.png)

**Comment by tomoki1207** [comment]
It might be fixed by 1.2.2.
Please check it. Thank you.

**Comment by heziiop** [comment]
Tried v1.2.2, it works now, thank you!
