### ISSUE TITLE
Autofocus pdf on editor focus

### ISSUE THREAD

**Issue by jameshamm** [tomoki1207/vscode-pdfviewer#16]
### Setup
1. Open one editor with multiple pdfs, or multiple editors where one had an open pdf.
2. Lose focus of a tab with an open pdf (ctrl+tab, ctrl+[num] with multiple editors, click away
3. Refocus the tab with the pdf, without clicking on the pdf itself (ctrl+tab back, ctrl+[num], click the titlebar of the tab)

### Issue
Scrolling through the pdf with the keyboard arrows does not scroll through the pdf. Instead nothing happens. (Aside +1 for scrolling with the mouse scroll wheel works even if the tab is not in focus.)

The tab itself is in focus, but the pdf is not, so keyboard shortcuts such as scrolling with the arrow keys fail.

### Proposed Fix
"Autofocus" the pdf reader when the editor tab is focused.

**Comment by tomoki1207** [comment]
@jameshamm Thank you for reporting.
This behavior might be caused by VSCode not this plugin.
Actually this plugin works same as the Markdown preview plugin, and I saw a same problem on the Markdown plugin.
