### ISSUE TITLE
pdf files should be able to open at reverse colors like in document viewer in ubuntu

### ISSUE THREAD

**Issue by 197419** [tomoki1207/vscode-pdfviewer#22]
pdf files should be able to open at reverse colors like in document viewer in ubuntu:

like this (with eye color safe reversed black background):

![image](https://user-images.githubusercontent.com/8404792/40042994-d04ec2ec-582b-11e8-9f69-22efd8127992.png)

not like this (not with eye tired original white background):

![image](https://user-images.githubusercontent.com/8404792/40043061-01e47842-582c-11e8-9566-f73e409bda41.png)

**Comment by tomoki1207** [comment]
Close for aggregating.
If you want other features, please comment to the new issue.
