### ISSUE TITLE
Sometimes I have to confirm opening "The file is not displayed in the editor because..."

### ISSUE THREAD

**Issue by gandalfsaxe** [tomoki1207/vscode-pdfviewer#26]
For some PDFs this text comes up and I have to confirm every time I want to open a PDF:

> The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?

For others PDFs it opens without having to confirm.

This seems related to Microsoft/vscode/issues/1218. Would it be possible for you to simply open PDFs every time without having to confirm? Otherwise I guess we'll need to make an issue with Microsoft/vscode.

To illustrate, some works fine:

![](https://i.imgur.com/wZe5A8G.gif)

Others does not:

![](https://i.imgur.com/lApDPAV.gif)

**Comment by tomoki1207** [comment]
Because change api for display preview, it might be resolved.
