### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by Jonatino** [tomoki1207/vscode-pdfviewer#3]
Can we please get proper scaling so PDF's aren't being stretched? 

https://dl.dropboxusercontent.com/u/91292881/ShareX/2016/11/Code%20-%20Insiders_2016-11-24_21-16-11.png

Thanks (Great job on the extension :D)

**Comment by tomoki1207** [comment]
Fixed this issue on v0.1.0.
Thank you.
