### ISSUE TITLE
PDF viewing broken in OSX VSCode 1.28.2

### ISSUE THREAD

**Issue by richardxu100** [tomoki1207/vscode-pdfviewer#30]
A few days ago, I found this plugin not working properly, displaying this image when clicking on a PDF: 

<img width="1276" alt="screen shot 2018-11-10 at 5 21 16 pm" src="https://user-images.githubusercontent.com/13954830/48306782-649ac400-e50d-11e8-82e0-8d0bb1242224.png">
I thought this error might have to do with my using Firefox as my default web browser, but switching to Chrome hasn't resolved my issue.

**Comment by tomoki1207** [comment]
Could you tell me your environment?
+ OS
+ VSCode version
+ This extension version

**Comment by richardxu100** [comment]
Hey Tomoki!

Here are the details of my environment:

**OS**: OSX Mojave 10.14.1
**VSCode**: 1.28.2
**Extension Version**: 0.4.0 (I think. I attached a picture of my version of the extension)

<img width="638" alt="screen shot 2018-11-12 at 1 38 42 pm" src="https://user-images.githubusercontent.com/13954830/48367976-5b7e3400-e680-11e8-9259-e4da3f6dfbc9.png">

**Comment by richardxu100** [comment]
Hey Tomoki!

I found the bug. I disabled all of my extensions, re-enabled vscode pdf, and it worked just as before. Thanks for the help and wonderful vscode extension!
