### ISSUE TITLE
Blackscreen 

### ISSUE THREAD

**Issue by DoganM95** [tomoki1207/vscode-pdfviewer#32]
When i open a pdf using this extensionit seems to load the pdf, but after a second it just blackscreens.
i also tried it after disabling all other extensions and after checking my vscode settings.json, no luck.
![image](https://user-images.githubusercontent.com/38842553/49042055-4698b900-f1c7-11e8-8ac9-eb6945250cd9.png)

**Comment by tomoki1207** [comment]
dup #31 .
Unfortunately it hasn't been fixed. Sorry for inconvenience.
