### ISSUE TITLE
Extension removed due to security incident in NPM package "event-stream"

### ISSUE THREAD

**Issue by cstuder** [tomoki1207/vscode-pdfviewer#33]
FYI: The NPM package "event-stream" [has been compromised](https://github.com/dominictarr/event-stream/issues/116). This lead Microsoft to [unlist and forcibly de-install](https://code.visualstudio.com/blogs/2018/11/26/event-stream) the affected extensions.

tomoki1207.pdf is afffected as well.

I got a popup this morning which informed me about the de-installation. According to Microsoft, you'll have to fix the dependency and publish a new version for it to re-appear in the Marketplace.

**Comment by Jiab77** [comment]
@cstuder Just got the same popup few minutes a go and you finally gave me the explanation! Thanks a lot!

**Comment by emackey** [comment]
Thanks for the link to the blog post.  I'm the developer of one of the listed extensions, `cesium.gltf-vscode`.  I pushed an update this morning to fix it, but hours later the marketplace still lists it as "malicious."

I love VSCode, and I love many aspects of the ecosystem of extensions, but the handling of this issue has been extremely poor for extension developers.  End users had extensions yanked out from under them, but the developers of those extensions were never notified.  Even after pushing a fix, the marketplace sends the developer a "success!" email, while continuing to show a "Malware" banner to end users.

The developer portal shows no sign of the problem.  It does not indicate that the extension is flagged as malware.  It does not offer any link to get help or even re-run the malware test.

I'm concerned that my users have lost faith in the security of my extension.  The messaging inside of VSCode itself appears to indicate that it is the extension's fault the malware is there.  In fact the malware came in as a sub-dependency of the VSCode extension API itself (the `vscode` reference in `package.json`), so any extension that was updated and published during the time the NPM compromise went un-detected will contain a copy.

Even after this is all fixed and resolved, thousands of former users of my extension will have to manually re-download and re-install, hoping that it's safe this time.

I love you guys, but, I think there should be a review of how these things are handled, indicated, and communicated.

**Comment by auchenberg** [comment]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) [ ] Fix the extension, submit an update to the marketplace
2) [ ] Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

/k

**Comment by CwjXFH** [comment]
I was affected not by bitcoin but by my inability to view PDF documents in vscode :joy:.

**Comment by xaduha** [comment]
I'm not that bother by the vulnerability, but I am bothered by the fact that MS uninstalled it without my permission. Does anyone know whether there is a setting to prevent that?

**Comment by tomoki1207** [comment]
@cstuder Thanks a lot for information!

@all
I just updated for recovery.
Please just a moment.

**Comment by Jiab77** [comment]
> I'm not that bother by the vulnerability, but I am bothered by the fact that MS uninstalled it without my permission. Does anyone know whether there is a setting to prevent that?

got the same... it would be better to just popup the notification and let us decide what to do instead of force removing of the extension and just give us a notification saying "we have removed the extension, please reload" WTF??? where is our right to take decisions?? @auchenberg

**Comment by cstuder** [comment]
I am very bothered by vulnerabilities and feel better knowing somebody is watching my back.

You can disable extensions auto updates with the settings `extensions.autoCheckUpdates` and `extensions.autoUpdate`. I don't know if that would help in this case.

And if you don't trust Microsoft at all, you can use [VSCodium](https://github.com/VSCodium/vscodium) as an alternate release of VS Code. 

We get into off-topic territory though, maybe post your opinion on https://github.com/Microsoft/vscode/issues/63837 .

**Comment by xaduha** [comment]
> You can disable extensions auto updates with the settings extensions.autoCheckUpdates and extensions.autoUpdate. I don't know if that would help in this case.

I tried it, doesn't work. I have it in a docker container, so I can reset it to a state that still has the extension, but it still gets deleted every time. And without Internet connection it doesn't even start.

**Comment by Jiab77** [comment]
@cstuder:
> I am very bothered by vulnerabilities and feel better knowing somebody is watching my back.
> 
> You can disable extensions auto updates with the settings `extensions.autoCheckUpdates` and `extensions.autoUpdate`. I don't know if that would help in this case.
> 
> And if you don't trust Microsoft at all, you can use [VSCodium](https://github.com/VSCodium/vscodium) as an alternate release of VS Code.
> 
> We get into off-topic territory though, maybe post your opinion on [Microsoft/vscode#63837](https://github.com/Microsoft/vscode/issues/63837) .

Well not so much off-topic. I got the same concerns so I don't want to disable the `autoUpdate`, it was just to referring to the message of @auchenberg which announce that Microsoft decided to tag as malicious and so remove the extension without asking the user first.

Notify is required for sure but a different tagging (still tagged as *malicious* in vscode extension search) and different behavious would be better.

@tomoki1207 thanks for your great work, just waiting on Microsoft to unlock your extension. :+1:

**Comment by tomoki1207** [comment]
It seems to be republished.
