### ISSUE TITLE
PDF.js - Failed to fetch

### ISSUE THREAD

**Issue by csaar95** [tomoki1207/vscode-pdfviewer#37]
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Datum: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Betriebssystem: Windows_NT x64 10.0.17134

----

Some PDF-files aren't working with following error message:
![](https://i.gyazo.com/82024ad4e8bb5cc28693989da87fece8.png)

**Comment by tomoki1207** [comment]
@csaar95 It was updated. Please retry it?

**Comment by csaar95** [comment]
@tomoki1207 seems like it's working now, thanks.

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/61571320-670fcf00-aa47-11e9-9d29-1ab445758ad1.png)
Still.
