### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by shunmian** [tomoki1207/vscode-pdfviewer#38]
It will be great if this extension supports dark mode.

**Comment by frankspanks** [comment]
I have the same problem too.. going to try find a way to fix it!

**Comment by pdtran3k6** [comment]
@shunmian like inverted pdf pages (white text, black background)?

**Comment by shunmian** [comment]
@pdtran3k6 Yes, exactly, which is more friendly for long time reading.

**Comment by tomoki1207** [comment]
duplicate of #22.
