### ISSUE TITLE
not work !

### ISSUE THREAD

**Issue by manageryzy** [tomoki1207/vscode-pdfviewer#4]
vscode version : 1.7.2 
windows version: windows 10 14971 preview 161111-1700

show "The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding"

I can open it before I install this extension with the default text editor

here are the console output , but I found nothing here :(

> workbench.main.js:30 Overwriting extension <<.m>> to now point to mime <<text/x-matlab>>
workbench.main.js:66 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41008  for  terminal.run
workbench.main.js:66 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  40993  for  terminal.stop
workbench.main.js:66 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  40995  for  PowerShell.ExpandAlias
workbench.main.js:62 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.showOutput
workbench.main.js:62 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.run
workbench.main.js:62 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.rerun-last-script
workbench.main.js:62 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.terminate-script
workbench.main.js:62 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.test
workbench.main.js:121 [Extension Host] vscode-icons is active!
workbench.main.js:121 [Extension Host] Activating extension `shalldie.background` failed: EPERM: operation not permitted, open 'c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css'.I.logExtensionHostMessage @ workbench.main.js:121I.onMessaage @ workbench.main.js:121(anonymous function) @ workbench.main.js:121emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
workbench.main.js:121 [Extension Host] Activating extension `shalldie.background` failed:  EPERM: operation not permitted, open 'c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css'I.logExtensionHostMessage @ workbench.main.js:121I.onMessaage @ workbench.main.js:121(anonymous function) @ workbench.main.js:121emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
workbench.main.js:121 [Extension Host] Here is the error stack:  Error: EPERM: operation not permitted, open 'c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Background.uninstall (C:\Users\manag\.vscode\extensions\shalldie.background-1.1.7\src\background.js:158:12)
    at Background.removeOld (C:\Users\manag\.vscode\extensions\shalldie.background-1.1.7\src\background.js:96:18)
    at Background.init (C:\Users\manag\.vscode\extensions\shalldie.background-1.1.7\src\background.js:38:26)
    at new Background (C:\Users\manag\.vscode\extensions\shalldie.background-1.1.7\src\background.js:25:14)
    at activate (C:\Users\manag\.vscode\extensions\shalldie.background-1.1.7\extension.js:25:32)
    at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:14861)
    at Function.t._callActivate (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:14644)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:14516
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:5732)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9310)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:11138)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10579)
workbench.main.js:101 Activating extension `shalldie.background` failed: EPERM: operation not permitted, open 'c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css'.t.$localShowMessage @ workbench.main.js:101e.handle @ workbench.main.js:100s @ workbench.main.js:49f @ workbench.main.js:49_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
workbench.main.js:121 [Extension Host] Spellchecker now active!

**Comment by tomoki1207** [comment]
@manageryzy
It is strange that it was displayed before installation.
Please tell me the followings.
- Is it not working always, or on specific file?
- Size of the file causing this issue.
- Does file name when mouse hover on tab includes '.rendered' ?

**Comment by manageryzy** [comment]
- always goes error
- pdf is less than 50k
-
![image](https://cloud.githubusercontent.com/assets/6567674/20932891/2d148c36-bc11-11e6-8054-d48ad99edc7d.png)

**Comment by tomoki1207** [comment]
@manageryzy Thank you for the detailed report.
It seems this extension didn't trigger cause of VSCode decide to the file is binary in first.

Is [this](https://github.com/posquit0/Awesome-CV/blob/master/examples/coverletter.pdf) your file tried to open?
In my environment, it could open correctly. 🤔 

This extension is using [PDF.js](https://mozilla.github.io/pdf.js/).
Could you visit this [demo site](https://mozilla.github.io/pdf.js/web/viewer.html) and try open your pdf files? (click open-file icon in upper right)

**Comment by robbeofficial** [comment]
I have the same issue. It simply shows "The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding" 

Your coverletter.pdf also does not work (document area remains blank). 

My document works (~22 mb) works perfectly with the PDF.js demo though. 

I'm running VSCode on Ubuntu
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

**Comment by arashbehmand** [comment]
regarding to [this](https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts), it seems that based on file size limit (`ResourceViewer.MAX_IMAGE_SIZE`), vscode decides to treat this file as binary, before this extension have a chance to render it.

**Comment by tomoki1207** [comment]
In addition to above, [this block](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/mime.ts#L85-L92) is deciding mime type of file. In case of it decided mime is binary , our extension cannot render the file too.

But, even these reasons the following behavior cannot be explained. 🤔 
> I can open it before I install this extension with the default text editor

**Comment by borablanca** [comment]
I had the same issue. However now I can open pdfs that I couldn't before with the context menu (right clicking on the file tree and click View PDF).

**Comment by Vey** [comment]
Thank you for your work on this extension! I'm really looking forward to full pdf support

I was also getting the error: "The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding". (vscode 1.15.0 x64. vscode-pdfviewer 0.2.0)

As a workaround, I found that a "not loadable pdf" was correctly displayed when converted to an older version of pdf (Acrobat 4 and later). 

Hope this helps

**Comment by tomoki1207** [comment]
Close since VSCode has been updated and its behavior might changed.
If you still have problems, please create another issue.
