### ISSUE TITLE
How to switch to text of uncompressed PDF specification 

### ISSUE THREAD

**Issue by abdulbadii** [tomoki1207/vscode-pdfviewer#41]
How to switch to simple text ?
i.e. how to toggle to view uncompressed PDF specification/language, the one that almost the same as Postscript language

**Comment by tomoki1207** [comment]
Sorry you can't.
It may be possible with the [LaTeX Workshop](https://marketplace.visualstudio.com/itemdetails?itemName=James-Yu.latex-workshop) plugin (but I haven't use it)
