### ISSUE TITLE
Update to PDF.js v2.1.266 planned?

### ISSUE THREAD

**Issue by JayJayJazz** [tomoki1207/vscode-pdfviewer#42]
Hi,

PDF.js was already updated to v2.1.266
Link: https://github.com/mozilla/pdf.js/releases

Any plans to update the plugin?

**Comment by tomoki1207** [comment]
We used to update PDF.js at the same time as adding new features and/or fixing bugs.
So we had no plans to update it independently unless that update let fix this plugin bugs.
Please tell us if you know it, we'll update ASAP.
