### ISSUE TITLE
"Open To the Side" option doesn't work for PDF files

### ISSUE THREAD

**Issue by renodubois** [tomoki1207/vscode-pdfviewer#43]
Hey there,

VSCode's built in "Open to the side" feature, which puts the selected file over to the right side of the screen doesn't work for PDFs using this extension. The file momentarily shows on the right side (the correct behavior) and then jumps back over to the main pane.

My setup:
macOS 10.14.4
VSCode 1.33.1
vscode-pdfviewer 0.5.0

**Comment by tomoki1207** [comment]
Extension is updated, it might be resolved.
Thanks for report.
