### ISSUE TITLE
PDF viewer ignores the group where file is open

### ISSUE THREAD

**Issue by renkun-ken** [tomoki1207/vscode-pdfviewer#47]
If I open a pdf file in group 2, some raw string is firstly showed in group 2, but then the pdf viewer appears in group 1.

It seems that the pdf viewer ignores which group the file is open in.

**Comment by tomoki1207** [comment]
extension is updated, could you try again?

**Comment by renkun-ken** [comment]
The problem no longer exists. Thanks!
