### ISSUE TITLE
Save/remember last used state (zoom, tool, view, etc)

### ISSUE THREAD

**Issue by Axel-Shark** [tomoki1207/vscode-pdfviewer#50]
Every time I open a PDF I have to close the left sidebar which displays the page previews (broken on my machine), change zoom to page-fit, and select the hand tool instead of the text selection tool. Is there any way to have these settings saved on exit or to add a settings string for the extension where these can be set manually? For the majority of my PDFs I use these settings.

Thanks for the work that's gone into this extension. It's indispensable.

**Comment by tomoki1207** [comment]
Thank you for waiting for a long time.
The new version supports setting default options(zoom, tool, ..) of the viewer.
If you're still using this extension, give it a try.

**Comment by NA-Dev** [comment]
Even when I use the settings to turn the sidebar off, it remains open every time I open a pdf. The only change is it is on pages instead of outline.

**Comment by tomoki1207** [comment]
@NA-Dev Could you attach a screenshot or gif of your settings and that behavior? 
And please tell me about your env(OS, VSCode version,...).

**Comment by tomoki1207** [comment]
I close this issue for aggregating.
If you want other features, please comment to the new issue.

@NA-Dev Please create a new issue and report details(screenshot, OS, and so on).
