### ISSUE TITLE
Key combination ([Ctrl] + [W]) tries to close more than 1 window

### ISSUE THREAD

**Issue by Nikolice** [tomoki1207/vscode-pdfviewer#51]
Issue Type: <b>Bug</b>

**Maybe that's not an extension-specific problem… I don't know.**

My set: OS “Simply Linux” by “BaseALT” of Russian Federation (with an “XFCE desktop environment”), and “VS Code Insiders” (with an extension “vscode-pdf”). Not tested in “Windows 10”.

To reproduce: 
1. Have some windows opened (three of them): 
→ Some files (two of them). Both – with unsaved changes;
→ A view of a “PDF”-file (not its “code”) – opened by an “vscode-pdf” extension.

2. Try to close the window of the “PDF”-file – by pressing a key-combination: [Ctrl]+[W].

As a result – a dialog appears, asking: “Whether to *save* the contents of *one* of the **previous** windows (where, some unsaved changes were)?”

So, my question is: should the [Ctrl]+[W] ask to close more than one window?

---------

Though, if I go to a “File” menu (of the “VS Code”) – I see: 
[Ctrl]+[W] → can close (either?):
- the “VSCode” editor;
- one window (of the opened set)…

If I click on the “Close” cross (icon button) of the “VS Code - PDF” window tab (at the inside – of the “VS Code” opened window tabs bar) – only one window closes, without asking to close something else.

--------

Extension version: 0.5.1
VS Code version: Code - Insiders 1.41.0-insider (a747d264d668a947eeacd3492b60df6ce8dee6b4, 2019-11-23T11:12:35.768Z)
OS version: Linux x64 4.19.72-std-def-alt1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-4020 APU with Radeon(tm) HD Graphics (2 x 2966)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.31GB (0.41GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Nikolice** [comment]
Tried it now in "Windows 10" with usual (non-insiders) version of "VS Code" – and got no problem.

**Comment by tomoki1207** [comment]
OK, please reopen when it is occurred again.
Thanks for information.
