### ISSUE TITLE
vscode display: conflict with latexworkshop 

### ISSUE THREAD

**Issue by weidongzhou1994** [tomoki1207/vscode-pdfviewer#55]
as title

**Comment by yonicd** [comment]
same

**Comment by tomoki1207** [comment]
It is great extension.

**Comment by yonicd** [comment]
this issue isnt going to be resolved?

**Comment by tomoki1207** [comment]
@yonicd This was resolved. We can show preview like normal editor now, so removed that command.

**Comment by yonicd** [comment]
ah ok. ty
