### ISSUE TITLE
Unable to display any PDF file after restarting VS Code

### ISSUE THREAD

**Issue by FJShen** [tomoki1207/vscode-pdfviewer#57]
If I leave the pdf files open in VS Code, exit and restart VS Code, then none of the pdf files will be displayed (the plugin reports "An error occurred while restoring view:pdf.preview"). I have to close the pdf files and reopen them again so as to view the file. 
![image](https://user-images.githubusercontent.com/25196473/77548409-e4b49600-6e84-11ea-830e-a47e759b1a0f.png)

**Comment by prshnt19** [comment]
I am also having the same issue. Sometimes I need to reopen it 2-3 times to view the pdf.

**Comment by tomoki1207** [comment]
Probably that error had occurred when creating webview in VSCode.
And by VSCode update, it seems fixed.
