### ISSUE TITLE
Scrollbar is not visible

### ISSUE THREAD

**Issue by Bno93** [tomoki1207/vscode-pdfviewer#68]
When I'm opening a pdf file in vscode the extension will show all ui components except the scrollbar on the right hand side.
I'm able to scroll via mouse wheel. 

![image](https://user-images.githubusercontent.com/8143328/86792764-171c8480-c06b-11ea-9822-2852c50dc766.png)

I have LaTex-Workshop installed but disabled in my current installation. 
My setup is VSCode V1.4.6.1 with vscode-pdfviewer V1.0.0 and texlab installed.

**Comment by tomoki1207** [comment]
It may have been fixed in VSCode 1.47.0 or later.
Please check again after upgrade VSCode.

**Comment by Bno93** [comment]
Hi @tomoki1207, 
I'm already up to date with my VSCode but still there is no scrollbar.
Also checked the dev tools:

```
[Embedded Page] Warning: Setting up fake worker.
webviewElement.ts:160 [Embedded Page] Refused to get unsafe header "Content-Disposition"
webviewElement.ts:160 [Embedded Page] PDF 166409edb7f1c6698efcf384437d5267 [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.4.456)
```

I don't know if the is helpfull.

**Comment by tomoki1207** [comment]
mmm...
What is your OS?
And is it possible to attach the file?

**Comment by Bno93** [comment]
I work on windows 10 and on linux (ubuntu 20.04) also.

Attached you will find an example project with a pdf file.

[test.zip](https://github.com/tomoki1207/vscode-pdfviewer/files/4965973/test.zip)

**Comment by tomoki1207** [comment]
Thanks.
The scrollbar is visible at macOS even attached file.
BTW, is scrollbar shown at the other preview extension(e.g. markdown)?

**Comment by Bno93** [comment]
That's strange. 

When I preview a markdown file I'll get a scrollbar.

![image](https://user-images.githubusercontent.com/8143328/88508489-39a51c00-cfdf-11ea-8d9d-a8c3342f075b.png)

**Comment by tomoki1207** [comment]
In my win10(at VirtualBox), a scrollbar is shown...

Is scrollbar missing on every pdf?
And what happens if disable all extensions but this extension and try again?

**Comment by Bno93** [comment]
I noticed this at all PDF's open with this extension. 
I will test it with all other extensions disabled

**Comment by Bno93** [comment]
After disable all extensions but vscode-pdfviewer the scrollbar appears.
I noticed that Latex-Workshop installed but generally disabled.

**Comment by tomoki1207** [comment]
Ok, I'll close it.
Thanks for cooperation.
