### ISSUE TITLE
Japanese text not appearing on PDF

### ISSUE THREAD

**Issue by Aridez** [tomoki1207/vscode-pdfviewer#76]
The PDF can be downloaded [here](https://drive.google.com/file/d/1CGMq7QDND87NFkPBi3acZE-xnXP-fw_H/view).

Right on the first page the text is appearing blank:

![image](https://user-images.githubusercontent.com/22683419/91104294-c4744780-e66d-11ea-9d31-3f9fbd261600.png)

**Comment by tomoki1207** [comment]
fixed by #116.
