### ISSUE TITLE
Cannot Open via Command Palette 

### ISSUE THREAD

**Issue by Bigg-Iron** [tomoki1207/vscode-pdfviewer#9]
- 1. Opening a .pdf file from the 'Explorer' displays this message: "The file will not be displayed in the        editor because it is either binary, very large or uses an unsupported text encoding."

- 2. Trying to view as PDF via command palette results in following error: "error: Running the contributed command:'extension.pdf-preview' failed."
 
- 3. The only way this extension works is by right-clicking from explorer and selecting "view PDF".

**Comment by tomoki1207** [comment]
@sroprietary-poftware Thank you for reporting.
We can't handle files detected as binary (or too large, unsupported) from extension API. (FYI #4)
So, the (iii) is only way to show PDF file at now as you said.

**Comment by nitishxp** [comment]
@tomoki1207  can u tell the exact steps to open the file i am directly opening the file the raw content are being shown to me please help

**Comment by tomoki1207** [comment]
Close since VSCode has been updated and its behavior might changed.
If you still have problems, please create another issue.
